import type { Customer, DashboardStats, Meeting, SupportTicket, Segment } from "@/types";

export const dashboardStats: DashboardStats = {
  totalCustomers: 198,
  totalARR: 4850000,
  averageHealthScore: 78,
  atRiskCount: 12,
  upcomingRenewals: 18,
  renewalValue: 920000,
  npsScore: 72,
  churnRate: 2.4,
};

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "FilterLabs",
    logo: "/logos/filterlabs.png",
    brandLogo: "dropbox",
    website: "filterlabs.ai",
    category: undefined,
    industry: "Technology",
    healthScore: 92,
    healthStatus: "healthy",
    arr: 10188,
    mrr: 849,
    renewalDate: "2026-02-13",
    lastContact: "2024-01-28",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Enterprise", "Strategic", "Tech"],
    sentiment: "positive",
    productUsage: 87,
    supportTickets: {
      open: 1,
      resolved: 24,
    },
  },
  {
    id: "cust-002",
    name: "The Feast AI",
    logo: "/logos/feast.png",
    brandLogo: "adobe",
    website: "thefeast.ai",
    category: "SMB - APAC",
    industry: "Technology",
    healthScore: 78,
    healthStatus: "healthy",
    arr: 12752,
    mrr: 1063,
    renewalDate: "2026-03-20",
    lastContact: "2024-01-29",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["SMB", "APAC"],
    sentiment: "positive",
    productUsage: 72,
    supportTickets: {
      open: 2,
      resolved: 31,
    },
  },
  {
    id: "cust-003",
    name: "ClickzMedia",
    logo: "/logos/clickz.png",
    brandLogo: "microsoft",
    website: "clickzmedia.com",
    category: "MM - ROW",
    industry: "Media",
    healthScore: 45,
    healthStatus: "at-risk",
    arr: 10188,
    mrr: 849,
    renewalDate: "2026-02-11",
    lastContact: "2024-01-15",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["Mid-Market", "ROW"],
    sentiment: "negative",
    productUsage: 34,
    supportTickets: {
      open: 5,
      resolved: 12,
    },
  },
  {
    id: "cust-004",
    name: "FairMoney",
    logo: "/logos/fairmoney.png",
    brandLogo: "notion",
    website: "fairmoney.io",
    category: "SMB - APAC",
    industry: "Finance",
    healthScore: 85,
    healthStatus: "healthy",
    arr: 77280,
    mrr: 6440,
    renewalDate: "2026-02-15",
    lastContact: "2024-01-27",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["SMB", "APAC", "Finance"],
    sentiment: "positive",
    productUsage: 91,
    supportTickets: {
      open: 0,
      resolved: 8,
    },
  },
  {
    id: "cust-005",
    name: "Loopia Group",
    logo: "/logos/loopia.png",
    brandLogo: "twitch",
    website: "loopiagroup.com",
    category: "MM - ROW",
    industry: "Technology",
    healthScore: 62,
    healthStatus: "at-risk",
    arr: 14652,
    mrr: 1221,
    renewalDate: "2026-01-31",
    lastContact: "2024-01-22",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Mid-Market", "ROW"],
    sentiment: "neutral",
    productUsage: 55,
    supportTickets: {
      open: 3,
      resolved: 19,
    },
  },
  {
    id: "cust-006",
    name: "IntrCity SmartBus",
    logo: "/logos/intrcity.png",
    brandLogo: "stripe",
    website: "intrcity.com",
    category: "SMB - APAC",
    industry: "Transportation",
    healthScore: 28,
    healthStatus: "critical",
    arr: 25500,
    mrr: 2125,
    renewalDate: "2026-02-06",
    lastContact: "2024-01-10",
    csm: {
      id: "csm-003",
      name: "Emily Davis",
      avatar: "/avatars/emily.jpg",
    },
    tags: ["SMB", "APAC", "At Risk"],
    sentiment: "negative",
    productUsage: 18,
    supportTickets: {
      open: 8,
      resolved: 15,
    },
  },
  {
    id: "cust-007",
    name: "Acme Corporation",
    logo: "/logos/acme.png",
    brandLogo: "slack",
    website: "acme.com",
    category: "Enterprise - NA",
    industry: "Technology",
    healthScore: 92,
    healthStatus: "healthy",
    arr: 120000,
    mrr: 10000,
    renewalDate: "2026-06-15",
    lastContact: "2024-01-28",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Enterprise", "Strategic", "Tech"],
    sentiment: "positive",
    productUsage: 87,
    supportTickets: {
      open: 1,
      resolved: 24,
    },
  },
  {
    id: "cust-008",
    name: "Global Dynamics",
    logo: "/logos/global-dynamics.png",
    brandLogo: "spotify",
    website: "globaldynamics.io",
    category: "MM - ROW",
    industry: "Manufacturing",
    healthScore: 45,
    healthStatus: "at-risk",
    arr: 85000,
    mrr: 7083,
    renewalDate: "2026-03-20",
    lastContact: "2024-01-15",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["Mid-Market", "Manufacturing"],
    sentiment: "negative",
    productUsage: 34,
    supportTickets: {
      open: 5,
      resolved: 12,
    },
  },
  {
    id: "cust-009",
    name: "TechVentures Inc",
    logo: "/logos/techventures.png",
    brandLogo: "github",
    website: "techventures.io",
    category: "Enterprise - NA",
    industry: "Technology",
    healthScore: 88,
    healthStatus: "healthy",
    arr: 156000,
    mrr: 13000,
    renewalDate: "2026-05-10",
    lastContact: "2024-01-26",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Enterprise", "Tech"],
    sentiment: "positive",
    productUsage: 92,
    supportTickets: {
      open: 0,
      resolved: 18,
    },
  },
  {
    id: "cust-010",
    name: "CloudSync Solutions",
    logo: "/logos/cloudsync.png",
    brandLogo: "google",
    website: "cloudsync.dev",
    category: "SMB - NA",
    industry: "Technology",
    healthScore: 72,
    healthStatus: "healthy",
    arr: 48000,
    mrr: 4000,
    renewalDate: "2026-04-15",
    lastContact: "2024-01-20",
    csm: {
      id: "csm-003",
      name: "Emily Davis",
      avatar: "/avatars/emily.jpg",
    },
    tags: ["SMB", "Tech"],
    sentiment: "positive",
    productUsage: 68,
    supportTickets: {
      open: 2,
      resolved: 9,
    },
  },
  {
    id: "cust-011",
    name: "DataFlow Analytics",
    logo: "/logos/dataflow.png",
    brandLogo: "figma",
    website: "dataflow.ai",
    category: "MM - EMEA",
    industry: "Analytics",
    healthScore: 55,
    healthStatus: "at-risk",
    arr: 67000,
    mrr: 5583,
    renewalDate: "2026-02-28",
    lastContact: "2024-01-18",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["Mid-Market", "Analytics"],
    sentiment: "neutral",
    productUsage: 45,
    supportTickets: {
      open: 4,
      resolved: 15,
    },
  },
  {
    id: "cust-012",
    name: "PayRight Finance",
    logo: "/logos/payright.png",
    brandLogo: "paypal",
    website: "payright.com",
    category: "Enterprise - EMEA",
    industry: "Finance",
    healthScore: 94,
    healthStatus: "healthy",
    arr: 220000,
    mrr: 18333,
    renewalDate: "2026-07-01",
    lastContact: "2024-01-29",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Enterprise", "Finance", "Strategic"],
    sentiment: "positive",
    productUsage: 95,
    supportTickets: {
      open: 0,
      resolved: 32,
    },
  },
  {
    id: "cust-013",
    name: "MediaStream Pro",
    logo: "/logos/mediastream.png",
    brandLogo: "netflix",
    website: "mediastream.tv",
    category: "MM - NA",
    industry: "Media",
    healthScore: 38,
    healthStatus: "critical",
    arr: 54000,
    mrr: 4500,
    renewalDate: "2026-02-05",
    lastContact: "2024-01-08",
    csm: {
      id: "csm-003",
      name: "Emily Davis",
      avatar: "/avatars/emily.jpg",
    },
    tags: ["Mid-Market", "Media", "At Risk"],
    sentiment: "negative",
    productUsage: 22,
    supportTickets: {
      open: 7,
      resolved: 11,
    },
  },
  {
    id: "cust-014",
    name: "DevOps Central",
    logo: "/logos/devops.png",
    brandLogo: "linkedin",
    website: "devopscentral.io",
    category: "SMB - EMEA",
    industry: "Technology",
    healthScore: 81,
    healthStatus: "healthy",
    arr: 36000,
    mrr: 3000,
    renewalDate: "2026-05-20",
    lastContact: "2024-01-25",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["SMB", "Tech"],
    sentiment: "positive",
    productUsage: 78,
    supportTickets: {
      open: 1,
      resolved: 6,
    },
  },
  {
    id: "cust-015",
    name: "EcommerceHub",
    logo: "/logos/ecommerce.png",
    brandLogo: "amazon",
    website: "ecommercehub.shop",
    category: "MM - APAC",
    industry: "E-commerce",
    healthScore: 67,
    healthStatus: "at-risk",
    arr: 72000,
    mrr: 6000,
    renewalDate: "2026-03-10",
    lastContact: "2024-01-19",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Mid-Market", "E-commerce", "APAC"],
    sentiment: "neutral",
    productUsage: 58,
    supportTickets: {
      open: 3,
      resolved: 14,
    },
  },
  {
    id: "cust-016",
    name: "FinanceFlow",
    logo: "/logos/financeflow.png",
    brandLogo: "wise",
    website: "financeflow.app",
    category: "SMB - NA",
    industry: "Finance",
    healthScore: 76,
    healthStatus: "healthy",
    arr: 28000,
    mrr: 2333,
    renewalDate: "2026-04-25",
    lastContact: "2024-01-24",
    csm: {
      id: "csm-003",
      name: "Emily Davis",
      avatar: "/avatars/emily.jpg",
    },
    tags: ["SMB", "Finance"],
    sentiment: "positive",
    productUsage: 71,
    supportTickets: {
      open: 1,
      resolved: 5,
    },
  },
  {
    id: "cust-017",
    name: "DesignStudio Pro",
    logo: "/logos/designstudio.png",
    brandLogo: "framer",
    website: "designstudio.co",
    category: "SMB - EMEA",
    industry: "Design",
    healthScore: 89,
    healthStatus: "healthy",
    arr: 42000,
    mrr: 3500,
    renewalDate: "2026-06-15",
    lastContact: "2024-01-27",
    csm: {
      id: "csm-002",
      name: "Mike Johnson",
      avatar: "/avatars/mike.jpg",
    },
    tags: ["SMB", "Design"],
    sentiment: "positive",
    productUsage: 85,
    supportTickets: {
      open: 0,
      resolved: 7,
    },
  },
  {
    id: "cust-018",
    name: "WebBuilder Corp",
    logo: "/logos/webbuilder.png",
    brandLogo: "webflow",
    website: "webbuilder.dev",
    category: "MM - NA",
    industry: "Technology",
    healthScore: 52,
    healthStatus: "at-risk",
    arr: 58000,
    mrr: 4833,
    renewalDate: "2026-02-20",
    lastContact: "2024-01-12",
    csm: {
      id: "csm-001",
      name: "Sarah Chen",
      avatar: "/avatars/sarah.jpg",
    },
    tags: ["Mid-Market", "Tech"],
    sentiment: "neutral",
    productUsage: 41,
    supportTickets: {
      open: 4,
      resolved: 10,
    },
  },
];

export const mockSegments: Segment[] = [
  {
    id: "seg-001",
    name: "High Risk Accounts",
    description: "Accounts with health score below 50 or critical status",
    filters: {
      healthStatus: ["at-risk", "critical"],
    },
    color: "#ef4444",
  },
  {
    id: "seg-002",
    name: "Enterprise Accounts",
    description: "Large enterprise customers with ARR > $100k",
    filters: {
      minARR: 100000,
      tags: ["Enterprise"],
    },
    color: "#335cff",
  },
  {
    id: "seg-003",
    name: "Upcoming Renewals",
    description: "Accounts with renewals in the next 90 days",
    filters: {},
    color: "#fa7319",
  },
  {
    id: "seg-004",
    name: "SMB - APAC",
    description: "Small and medium businesses in Asia Pacific",
    filters: {
      tags: ["SMB", "APAC"],
    },
    color: "#1fc16b",
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "meet-001",
    customerId: "cust-001",
    title: "Quarterly Business Review",
    date: "2024-01-28",
    duration: 60,
    attendees: ["Sarah Chen", "John Smith (Acme)", "Lisa Wang (Acme)"],
    summary:
      "Positive QBR with Acme. They're seeing 3x ROI on the platform and planning to expand to two additional teams. Discussed new feature requests around reporting.",
    keyPoints: [
      "3x ROI achieved in Q4",
      "Planning expansion to marketing and sales teams",
      "Requested advanced reporting features",
      "Renewal confirmed for June",
    ],
    sentiment: "positive",
    actionItems: [
      {
        id: "action-001",
        title: "Send proposal for team expansion",
        assignee: "Sarah Chen",
        dueDate: "2024-02-05",
        completed: false,
      },
      {
        id: "action-002",
        title: "Schedule demo of new reporting features",
        assignee: "Sarah Chen",
        dueDate: "2024-02-10",
        completed: false,
      },
    ],
    tags: ["QBR", "Expansion", "Feature Request"],
  },
  {
    id: "meet-002",
    customerId: "cust-004",
    title: "Urgent Escalation Call",
    date: "2024-01-25",
    duration: 45,
    attendees: ["Emily Davis", "Tom Brown (TechFlow)", "VP Engineering (TechFlow)"],
    summary:
      "Critical meeting to address ongoing performance issues. Customer expressed frustration with response times and considering alternatives. Committed to weekly check-ins until resolved.",
    keyPoints: [
      "Performance issues affecting daily operations",
      "Customer evaluating competitor solutions",
      "Committed to dedicated support engineer",
      "Weekly check-ins scheduled",
    ],
    sentiment: "negative",
    actionItems: [
      {
        id: "action-003",
        title: "Assign dedicated support engineer",
        assignee: "Emily Davis",
        dueDate: "2024-01-26",
        completed: true,
      },
      {
        id: "action-004",
        title: "Escalate performance issues to engineering",
        assignee: "Emily Davis",
        dueDate: "2024-01-26",
        completed: true,
      },
    ],
    tags: ["Escalation", "At Risk", "Performance"],
  },
];

export const mockTickets: SupportTicket[] = [
  {
    id: "ticket-001",
    customerId: "cust-004",
    title: "API Response Time Degradation",
    description:
      "Experiencing significant slowdown in API response times, affecting production workflows.",
    status: "in-progress",
    priority: "critical",
    createdAt: "2024-01-20",
    updatedAt: "2024-01-29",
    assignee: "Tech Support Team",
    sentiment: "negative",
    tags: ["API", "Performance", "Critical"],
  },
  {
    id: "ticket-002",
    customerId: "cust-002",
    title: "Data Sync Issues with Salesforce",
    description: "Salesforce integration not syncing properly. Missing records in dashboard.",
    status: "open",
    priority: "high",
    createdAt: "2024-01-25",
    updatedAt: "2024-01-28",
    assignee: "Integration Team",
    sentiment: "negative",
    tags: ["Integration", "Salesforce", "Data Sync"],
  },
  {
    id: "ticket-003",
    customerId: "cust-001",
    title: "Feature Request: Custom Dashboard",
    description: "Would like ability to create custom dashboards with drag-and-drop widgets.",
    status: "open",
    priority: "low",
    createdAt: "2024-01-28",
    updatedAt: "2024-01-28",
    sentiment: "positive",
    tags: ["Feature Request", "Dashboard"],
  },
];
